# Generated by Django 3.2.4 on 2021-06-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name=' Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
