# Generated by Django 3.2.4 on 2021-06-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre de la categoria'),
        ),
    ]
